### ISSUE TITLE
Using conditions

### ISSUE THREAD

**Issue by rishab-yumist** [numtel/sails-mysql-live-select#1]
How do we use conditions in the liveFind() like where() and populate()?

Could you give a small example of where condition and join condition with the same.

**Comment by numtel** [comment]
Place your conditions in the first argument of the call to `liveFind()` according to the [waterline query language](http://sailsjs.org/documentation/concepts/models-and-orm/query-language). In my manual testing, it seems that the `where` key needs to be explicitly defined.

**Comment by rishab-yumist** [comment]
```
subscribers[req.socket.id] = Chat.liveFind({where: {'user':'Rishab'}},
    function(row, newRow, rowDeleted) {
      // Optional data invalidation callback
      // Check if data is invalidated by this row change
      console.log('Row data', row);
      return true;
    }
  ).on('update',
    function(diff, data) {
      // Results have changed, send to client
      sails.sockets.emit(req.socket.id, 'chatDiff', diff);
    }
  );
```

Doesn't work

  subscribers[req.socket.id] = Chat.liveFind({'user':'Rishab'},
        function(row, newRow, rowDeleted) {
          // Optional data invalidation callback
          // Check if data is invalidated by this row change
          console.log('Row data', row);
          return true;
        }
      ).on('update',
        function(diff, data) {
          // Results have changed, send to client
          sails.sockets.emit(req.socket.id, 'chatDiff', diff);
        }
      );

Doesn't work  
subscribers[req.socket.id] = Chat.liveFind({'id':3},
        function(row, newRow, rowDeleted) {
          // Optional data invalidation callback
          // Check if data is invalidated by this row change
          console.log('Row data', row);
          return true;
        }
      ).on('update',
        function(diff, data) {
          // Results have changed, send to client
          sails.sockets.emit(req.socket.id, 'chatDiff', diff);
        }
      );

**Comment by numtel** [comment]
That first example with `{where: {'user':'Rishab'}}` works fine for me.

**Comment by rishab-yumist** [comment]
@numtel Could you post the entire controller once?

**Comment by numtel** [comment]
It works with exactly what's in the repo except with that condition. There's nothing more I have to post.

**Comment by rishab-yumist** [comment]
Works @numtel . Thanks :)
